"""Component templates per assembly — deterministic decomposition fallback."""

COMPONENT_TEMPLATES: dict[str, list[dict]] = {
    "short_block": [
        {
            "id": "engine_block",
            "name": "Engine Block",
            "function": "Structural housing for combustion cylinders",
            "purpose": "Contain combustion forces and support crankshaft",
            "justification": "Required by structural_containment function",
            "serves_function_id": "structural_containment",
            "material": "Aluminum 356-T6",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "crankshaft",
            "name": "Crankshaft",
            "function": "Converts reciprocating motion to rotation",
            "purpose": "Primary motion conversion element",
            "justification": "Required by motion_conversion function",
            "serves_function_id": "motion_conversion",
            "material": "Forged Steel 4340",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "pistons",
            "name": "Pistons",
            "function": "Transfer combustion force to connecting rods",
            "purpose": "Seal combustion chamber and transmit force",
            "justification": "Required by motion_conversion function",
            "serves_function_id": "motion_conversion",
            "material": "2618 Forged Aluminum",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "connecting_rods",
            "name": "Connecting Rods",
            "function": "Link pistons to crankshaft",
            "purpose": "Transmit reciprocating force",
            "justification": "Required by motion_conversion function",
            "serves_function_id": "motion_conversion",
            "material": "Forged Steel 4340",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "cylinder_bores",
            "name": "Cylinder Bores",
            "function": "Guide piston motion with wear-resistant surface",
            "purpose": "Define combustion chamber geometry",
            "justification": "Required by combustion function",
            "serves_function_id": "combustion",
            "material": "Gray Cast Iron",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "main_bearings",
            "name": "Main Bearings",
            "function": "Support crankshaft rotation",
            "purpose": "Enable low-friction crankshaft support",
            "justification": "Required by motion_conversion function",
            "serves_function_id": "motion_conversion",
            "material": "Forged Steel 4340",
            "complexity_score": 0.7,
            "is_leaf": True,
        },
    ],
    "cylinder_head_assembly": [
        {
            "id": "cylinder_head",
            "name": "Cylinder Head",
            "function": "Seals combustion chamber and houses valves",
            "purpose": "Complete combustion chamber upper boundary",
            "justification": "Required by combustion function",
            "serves_function_id": "combustion",
            "material": "Aluminum 356-T6",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "valves",
            "name": "Valves",
            "function": "Control intake and exhaust gas flow",
            "purpose": "Enable gas exchange timing",
            "justification": "Required by air_induction function",
            "serves_function_id": "air_induction",
            "material": "Stainless Steel 21-4N",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "exhaust_valves",
            "name": "Exhaust Valves",
            "function": "Control exhaust gas flow",
            "purpose": "Enable exhaust gas evacuation at high temperature",
            "justification": "Required by combustion function",
            "serves_function_id": "combustion",
            "material": "Inconel 718",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "camshaft",
            "name": "Camshaft",
            "function": "Actuate valve timing",
            "purpose": "Synchronize valve events with crank position",
            "justification": "Required by combustion function",
            "serves_function_id": "combustion",
            "material": "Nitrided Steel",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "spark_plugs",
            "name": "Spark Plugs",
            "function": "Initiate combustion via spark",
            "purpose": "Ignition source for fuel-air mixture",
            "justification": "Required by ignition function",
            "serves_function_id": "ignition",
            "material": None,
            "complexity_score": 0.5,
            "is_leaf": True,
        },
    ],
    "fuel_system": [
        {
            "id": "fuel_pump",
            "name": "Fuel Pump",
            "function": "Pressurize fuel for injection",
            "purpose": "Deliver fuel at required pressure",
            "justification": "Required by fuel_delivery function",
            "serves_function_id": "fuel_delivery",
            "material": None,
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "fuel_injectors",
            "name": "Fuel Injectors",
            "function": "Atomize and meter fuel into combustion chamber",
            "purpose": "Precise fuel metering",
            "justification": "Required by fuel_delivery function",
            "serves_function_id": "fuel_delivery",
            "material": None,
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "fuel_rail",
            "name": "Fuel Rail",
            "function": "Distribute pressurized fuel to injectors",
            "purpose": "Common fuel supply manifold",
            "justification": "Required by fuel_delivery function",
            "serves_function_id": "fuel_delivery",
            "material": None,
            "complexity_score": 0.6,
            "is_leaf": True,
        },
    ],
    "cooling_system": [
        {
            "id": "radiator",
            "name": "Radiator",
            "function": "Reject heat from coolant to ambient air",
            "purpose": "Primary heat exchanger",
            "justification": "Required by thermal_management function",
            "serves_function_id": "thermal_management",
            "material": "Aluminum 356-T6",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "water_pump",
            "name": "Water Pump",
            "function": "Circulate coolant through engine",
            "purpose": "Maintain coolant flow",
            "justification": "Required by thermal_management function",
            "serves_function_id": "thermal_management",
            "material": None,
            "complexity_score": 0.7,
            "is_leaf": True,
        },
        {
            "id": "thermostat",
            "name": "Thermostat",
            "function": "Regulate coolant flow based on temperature",
            "purpose": "Maintain optimal operating temperature",
            "justification": "Required by thermal_management function",
            "serves_function_id": "thermal_management",
            "material": None,
            "complexity_score": 0.5,
            "is_leaf": True,
        },
    ],
    "lubrication_system": [
        {
            "id": "oil_pan",
            "name": "Oil Pan",
            "function": "Reservoir for lubricating oil",
            "purpose": "Store and collect oil",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": "Aluminum 356-T6",
            "complexity_score": 0.6,
            "is_leaf": True,
        },
        {
            "id": "oil_pickup_tube",
            "name": "Oil Pickup Tube",
            "function": "Draw oil from pan sump",
            "purpose": "Supply oil to pump inlet",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.5,
            "is_leaf": True,
        },
        {
            "id": "oil_pump",
            "name": "Oil Pump",
            "function": "Circulate lubricating oil under pressure",
            "purpose": "Deliver oil to bearing surfaces",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.7,
            "is_leaf": True,
        },
        {
            "id": "pressure_relief_valve",
            "name": "Pressure Relief Valve",
            "function": "Limit maximum oil system pressure",
            "purpose": "Protect oil galleries and seals",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.4,
            "is_leaf": True,
        },
        {
            "id": "oil_filter",
            "name": "Oil Filter",
            "function": "Remove contaminants from lubricating oil",
            "purpose": "Protect bearing surfaces from wear",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.5,
            "is_leaf": True,
        },
        {
            "id": "main_oil_gallery",
            "name": "Main Oil Gallery",
            "function": "Distribute pressurized oil through engine block",
            "purpose": "Feed bearings and moving surfaces",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.6,
            "is_leaf": True,
        },
        {
            "id": "thermal_fluid_nozzle",
            "name": "Thermal Fluid Nozzle",
            "function": "Spray oil onto reciprocating undersides",
            "purpose": "Reject reciprocating crown heat",
            "justification": "Required by lubrication and thermal_management functions",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.5,
            "is_leaf": True,
        },
    ],
    "electrical_system": [
        {
            "id": "ignition_coil",
            "name": "Ignition Coil",
            "function": "Generate high-voltage spark",
            "purpose": "Provide ignition energy",
            "justification": "Required by ignition function",
            "serves_function_id": "ignition",
            "material": None,
            "complexity_score": 0.6,
            "is_leaf": True,
        },
        {
            "id": "ecu",
            "name": "Engine Control Unit",
            "function": "Compute ignition and fuel timing",
            "purpose": "Real-time engine management",
            "justification": "Required by ignition function",
            "serves_function_id": "ignition",
            "material": None,
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "sensors",
            "name": "Engine Sensors",
            "function": "Measure temperature, pressure, and position",
            "purpose": "Provide feedback for engine control",
            "justification": "Required by ignition function",
            "serves_function_id": "ignition",
            "material": None,
            "complexity_score": 0.6,
            "is_leaf": True,
        },
    ],
    "fan_module": [
        {
            "id": "fan_blades",
            "name": "Fan Blades",
            "function": "Accelerate bypass air for thrust",
            "purpose": "Primary propulsive element in high-bypass turbofan",
            "justification": "Required by exhaust_acceleration function",
            "serves_function_id": "exhaust_acceleration",
            "material": "Titanium 6Al-4V",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "fan_disk",
            "name": "Fan Disk",
            "function": "Retain and support fan blades",
            "purpose": "Structural attachment for fan blades",
            "justification": "Required by exhaust_acceleration function",
            "serves_function_id": "exhaust_acceleration",
            "material": "Titanium 6Al-4V",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
    ],
    "compressor_module": [
        {
            "id": "compressor_rotor",
            "name": "Compressor Rotor",
            "function": "Multi-stage axial compression of core air",
            "purpose": "Raise pressure ratio for combustion",
            "justification": "Required by air_compression function",
            "serves_function_id": "air_compression",
            "material": "Titanium 6Al-4V",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "compressor_stator",
            "name": "Compressor Stator",
            "function": "Guide airflow between rotor stages",
            "purpose": "Optimize compression efficiency",
            "justification": "Required by air_compression function",
            "serves_function_id": "air_compression",
            "material": "Inconel 718",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
    ],
    "combustor_module": [
        {
            "id": "combustor_liner",
            "name": "Combustor Liner",
            "function": "Contain high-temperature combustion",
            "purpose": "Withstand combustor operating temperatures",
            "justification": "Required by combustion function",
            "serves_function_id": "combustion",
            "material": "Inconel 718",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "fuel_nozzles",
            "name": "Fuel Nozzles",
            "function": "Atomize fuel into combustor",
            "purpose": "Uniform fuel-air mixing",
            "justification": "Required by fuel_delivery function",
            "serves_function_id": "fuel_delivery",
            "material": "Inconel 718",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
    ],
    "turbine_module": [
        {
            "id": "turbine_blades",
            "name": "Turbine Blades",
            "function": "Extract energy from hot gas stream",
            "purpose": "Drive compressor and fan spools",
            "justification": "Required by energy_extraction function",
            "serves_function_id": "energy_extraction",
            "material": "Inconel 718",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "turbine_disk",
            "name": "Turbine Disk",
            "function": "Retain turbine blades under centrifugal load",
            "purpose": "Structural support for turbine blades",
            "justification": "Required by energy_extraction function",
            "serves_function_id": "energy_extraction",
            "material": "Inconel 718",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
    ],
    "exhaust_module": [
        {
            "id": "exhaust_nozzle",
            "name": "Exhaust Nozzle",
            "function": "Accelerate exhaust gas for thrust",
            "purpose": "Convert gas energy to momentum",
            "justification": "Required by exhaust_acceleration function",
            "serves_function_id": "exhaust_acceleration",
            "material": "Inconel 718",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
    ],
    "accessory_gearbox": [
        {
            "id": "agb_housing",
            "name": "AGB Housing",
            "function": "Enclose accessory drive gears",
            "purpose": "Contain and align accessory drive",
            "justification": "Required by accessory_drive function",
            "serves_function_id": "accessory_drive",
            "material": "Aluminum 356-T6",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "agb_gears",
            "name": "AGB Gears",
            "function": "Transfer power to accessories",
            "purpose": "Drive fuel pumps and generators",
            "justification": "Required by accessory_drive function",
            "serves_function_id": "accessory_drive",
            "material": "Nitrided Steel",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
    ],
    "input_shaft_assembly": [
        {
            "id": "input_shaft",
            "name": "Input Shaft",
            "function": "Receive torque from power source",
            "purpose": "Primary input interface",
            "justification": "Required by torque_transmission function",
            "serves_function_id": "torque_transmission",
            "material": "Nitrided Steel",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
        {
            "id": "input_bearings",
            "name": "Input Bearings",
            "function": "Support input shaft under radial and axial load",
            "purpose": "Enable low-friction rotation",
            "justification": "Required by shaft_support function",
            "serves_function_id": "shaft_support",
            "material": "SAE 660 Bronze",
            "complexity_score": 0.7,
            "is_leaf": True,
        },
    ],
    "gear_train": [
        {
            "id": "primary_gears",
            "name": "Primary Gear Pair",
            "function": "First stage speed/torque transformation",
            "purpose": "Initial ratio reduction or increase",
            "justification": "Required by gear_meshing function",
            "serves_function_id": "gear_meshing",
            "material": "Nitrided Steel",
            "complexity_score": 1.0,
            "is_leaf": True,
        },
        {
            "id": "secondary_gears",
            "name": "Secondary Gear Pair",
            "function": "Additional ratio stages",
            "purpose": "Achieve target output ratio",
            "justification": "Required by gear_meshing function",
            "serves_function_id": "gear_meshing",
            "material": "Nitrided Steel",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
        {
            "id": "synchronizers",
            "name": "Synchronizers",
            "function": "Match gear speeds during shifts",
            "purpose": "Enable smooth ratio changes",
            "justification": "Required by ratio_selection function",
            "serves_function_id": "ratio_selection",
            "material": "Nitrided Steel",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
    ],
    "output_shaft_assembly": [
        {
            "id": "output_shaft",
            "name": "Output Shaft",
            "function": "Deliver transformed torque to load",
            "purpose": "Primary output interface",
            "justification": "Required by torque_transmission function",
            "serves_function_id": "torque_transmission",
            "material": "Nitrided Steel",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
        {
            "id": "output_bearings",
            "name": "Output Bearings",
            "function": "Support output shaft under load",
            "purpose": "Enable low-friction rotation",
            "justification": "Required by shaft_support function",
            "serves_function_id": "shaft_support",
            "material": "SAE 660 Bronze",
            "complexity_score": 0.7,
            "is_leaf": True,
        },
    ],
    "housing": [
        {
            "id": "gearbox_housing",
            "name": "Gearbox Housing",
            "function": "Structural enclosure for gear train",
            "purpose": "Maintain alignment and retain lubricant",
            "justification": "Required by structural_housing function",
            "serves_function_id": "structural_housing",
            "material": "Aluminum 356-T6",
            "complexity_score": 0.9,
            "is_leaf": True,
        },
    ],
    "gearbox_lubrication_system": [
        {
            "id": "gearbox_oil_pump",
            "name": "Oil Pump",
            "function": "Circulate gear lubricant",
            "purpose": "Deliver oil to meshing surfaces",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.7,
            "is_leaf": True,
        },
        {
            "id": "gearbox_oil_filter",
            "name": "Oil Filter",
            "function": "Remove wear particles from oil",
            "purpose": "Protect gear surfaces",
            "justification": "Required by lubrication function",
            "serves_function_id": "lubrication",
            "material": None,
            "complexity_score": 0.5,
            "is_leaf": True,
        },
    ],
    "shift_mechanism": [
        {
            "id": "shift_fork",
            "name": "Shift Fork",
            "function": "Engage and disengage gear pairs",
            "purpose": "Mechanical ratio selection",
            "justification": "Required by ratio_selection function",
            "serves_function_id": "ratio_selection",
            "material": "Forged Steel 4340",
            "complexity_score": 0.8,
            "is_leaf": True,
        },
        {
            "id": "shift_actuator",
            "name": "Shift Actuator",
            "function": "Apply force to shift fork",
            "purpose": "Driver or automated shift input",
            "justification": "Required by ratio_selection function",
            "serves_function_id": "ratio_selection",
            "material": None,
            "complexity_score": 0.7,
            "is_leaf": True,
        },
    ],
}

GENERIC_COMPONENT_NAMES = frozenset(
    {"sub component", "sub_component", "generic sub-component", "generic component"}
)
