"""Material catalog with physics properties."""

MATERIAL_CATALOG: dict[str, dict] = {
    "al_356_t6": {
        "name": "Aluminum 356-T6",
        "density_kg_m3": 2680,
        "yield_strength_mpa": 230,
        "fatigue_strength_mpa": 95,
        "thermal_conductivity_w_mk": 151,
        "temperature_limit_c": 200,
        "relative_cost": 1.0,
        "suitable_for": ["engine_block", "cylinder_head", "structural_housing", "oil_pan"],
    },
    "al_2618": {
        "name": "2618 Forged Aluminum",
        "density_kg_m3": 2760,
        "yield_strength_mpa": 440,
        "fatigue_strength_mpa": 125,
        "thermal_conductivity_w_mk": 150,
        "temperature_limit_c": 200,
        "relative_cost": 1.8,
        "suitable_for": ["piston", "high_rpm_piston"],
    },
    "al_4032": {
        "name": "4032 Forged Aluminum",
        "density_kg_m3": 2680,
        "yield_strength_mpa": 380,
        "fatigue_strength_mpa": 110,
        "thermal_conductivity_w_mk": 155,
        "temperature_limit_c": 200,
        "relative_cost": 1.5,
        "suitable_for": ["piston"],
    },
    "forged_steel_4340": {
        "name": "Forged Steel 4340",
        "density_kg_m3": 7850,
        "yield_strength_mpa": 710,
        "fatigue_strength_mpa": 350,
        "thermal_conductivity_w_mk": 44,
        "temperature_limit_c": 400,
        "relative_cost": 1.4,
        "suitable_for": ["crankshaft", "connecting_rod", "bearing_cap", "flywheel"],
    },
    "cast_iron_gray": {
        "name": "Gray Cast Iron",
        "density_kg_m3": 7200,
        "yield_strength_mpa": 200,
        "fatigue_strength_mpa": 90,
        "thermal_conductivity_w_mk": 52,
        "temperature_limit_c": 500,
        "relative_cost": 0.8,
        "suitable_for": ["cylinder_liner", "engine_block"],
    },
    "ti_6al4v": {
        "name": "Titanium 6Al-4V",
        "density_kg_m3": 4430,
        "yield_strength_mpa": 880,
        "fatigue_strength_mpa": 510,
        "thermal_conductivity_w_mk": 7,
        "temperature_limit_c": 600,
        "relative_cost": 8.0,
        "suitable_for": ["connecting_rod", "high_rpm_connecting_rod", "valve", "exhaust", "compressor_blade"],
    },
    "in718": {
        "name": "Inconel 718",
        "density_kg_m3": 8190,
        "yield_strength_mpa": 1034,
        "fatigue_strength_mpa": 520,
        "thermal_conductivity_w_mk": 11,
        "temperature_limit_c": 700,
        "relative_cost": 12.0,
        "suitable_for": ["exhaust_valve", "turbine_blade", "combustor", "high_temp_housing"],
    },
    "stainless_steel_21_4n": {
        "name": "Stainless Steel 21-4N",
        "density_kg_m3": 7800,
        "yield_strength_mpa": 650,
        "fatigue_strength_mpa": 300,
        "thermal_conductivity_w_mk": 20,
        "temperature_limit_c": 750,
        "relative_cost": 3.0,
        "suitable_for": ["intake_valve", "valve"],
    },
    "nitrided_steel": {
        "name": "Nitrided Steel",
        "density_kg_m3": 7850,
        "yield_strength_mpa": 900,
        "fatigue_strength_mpa": 420,
        "thermal_conductivity_w_mk": 44,
        "temperature_limit_c": 350,
        "relative_cost": 2.2,
        "suitable_for": ["camshaft", "gear", "shaft", "bearing_race"],
    },
    "bronze_sae660": {
        "name": "SAE 660 Bronze",
        "density_kg_m3": 8860,
        "yield_strength_mpa": 170,
        "fatigue_strength_mpa": 75,
        "thermal_conductivity_w_mk": 59,
        "temperature_limit_c": 200,
        "relative_cost": 1.7,
        "suitable_for": ["bearing", "bushing", "main_bearing", "worm_gear"],
    },
}

MATERIAL_ASSIGNMENTS: dict[str, str] = {
    "engine_block": "al_356_t6",
    "cylinder_head": "al_356_t6",
    "cylinder_bore": "cast_iron_gray",
    "cylinder_liner": "cast_iron_gray",
    "crankshaft": "forged_steel_4340",
    "connecting_rod": "forged_steel_4340",
    "piston": "al_2618",
    "intake_valve": "stainless_steel_21_4n",
    "exhaust_valve": "in718",
    "valve": "stainless_steel_21_4n",
    "camshaft": "nitrided_steel",
    "bearing": "bronze_sae660",
    "main_bearing": "bronze_sae660",
    "flywheel": "forged_steel_4340",
    "oil_pan": "al_356_t6",
    "gear": "nitrided_steel",
    "shaft": "nitrided_steel",
    "turbine_blade": "in718",
    "compressor_blade": "ti_6al4v",
    "combustor": "in718",
    "water_jacket": "al_356_t6",
}
